layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  sort_by options:
  #   - pushed
  #  - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - news

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: damianperera
  # mastodon: your_username
  medium: damianperera
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: gRPC
    web_url: https://grpc.io/
    image_url: https://grpc.io/img/logos/grpc-icon-color.png

  - name: Spring
    web_url: https://spring.io/
    image_url: https://spring.io/images/spring-logo-9146a4d3298760c2e7e49595184e1975.svg

  - name: Amazon Web Services
    web_url: https://aws.amazon.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png
