layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  sort_by options:
  #   - pushed
  #  - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - news

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: damianperera
  # mastodon: your_username
  medium: damianperera
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: damianperera
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: OpenWrt
    web_url: https://openwrt.org/
    image_url: https://avatars.githubusercontent.com/u/2528830?s=280&v=4

  - name: Raspberry Pi
    web_url: https://www.raspberrypi.com/software/
    image_url: https://upload.wikimedia.org/wikipedia/de/thumb/c/cb/Raspberry_Pi_Logo.svg/1200px-Raspberry_Pi_Logo.svg.png

  - name: OMV
    web_url: https://www.openmediavault.org/
    image_url: https://avatars.githubusercontent.com/u/1897994?s=280&v=4
